export const steps: any = [
  {
    tour: "tour1",
    steps: [
      {
        icon: <>👋</>,
        title: "Welcome to Your Website!",
        content: <>This interactive tour will show you how to customize your site.</>,
        selector: "#step0",
        side: "auto",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🖼️</>,
        title: "Customize Your Logo",
        content: <>Click on this area to upload your own logo image.</>,
        selector: "#step1",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>✏️</>,
        title: "Edit Title",
        content: <>text can be edited. Try clicking and typing!</>,
        selector: "#step2",
        side: "bottom",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>✏️</>,
        title: "Edit text",
        content: <>also this!</>,
        selector: "#step3",
        side: "right",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>🎨</>,
        title: "Color Toolbar",
        content: <>This toolbar lets you customize your site&apos;s color scheme.</>,
        selector: "#toolbar",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>🔄</>,
        title: "Try Different Colors",
        content: <>Click here to randomly generate new color schemes for your site.</>,
        selector: "#randomize",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>💾</>,
        title: "Save Your Work",
        content: <>When you&apos;re done, click here to export your design as a ZIP file.</>,
        selector: "#export",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>🎉</>,
        title: "All Set!",
        content: <>You&apos;re ready to create your own custom website. Happy designing!</>,
        selector: "#last",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 16,
      },
    ],
  },
  {
    tour: "colorTour",
    steps: [
      {
        icon: <>🎨</>,
        title: "Color Customization",
        content: <>Let&apos;s explore how to change your site&apos;s colors.</>,
        selector: "#toolbar",
        side: "top",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 11,
      },
      {
        icon: <>📝</>,
        title: "Text Color",
        content: <>This controls the main text color throughout your site.</>,
        selector: "#prim",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>🖼️</>,
        title: "Background Color",
        content: <>Change your site&apos;s background with this color picker.</>,
        selector: "#sec",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>🔘</>,
        title: "Primary Button Color",
        content: <>Style your main call-to-action buttons with this color.</>,
        selector: "#primbuttn",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>⚪</>,
        title: "Secondary Button Color",
        content: <>Set the color for your secondary action buttons.</>,
        selector: "#secbuttn",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
      {
        icon: <>✨</>,
        title: "Accent Color",
        content: <>This color adds visual interest and is used for highlights and effects.</>,
        selector: "#accent",
        side: "left",
        showControls: true,
        pointerPadding: 0,
        pointerRadius: 8,
      },
    ],
  },
];